
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar/page";
import SideBarStyleProvider from "./Providers/SideBarStyleProvider";
import ThemeProvider from "./Providers/ThemeProvider";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { auth } from '@clerk/nextjs/server';
import { redirect } from "next/dist/server/api-utils";
import Navigate from "./Providers/Navigate";
import NextTopLoader from 'nextjs-toploader';
import StyledComponentsRegistry from "./lib/registry";





const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TODO App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  
  const {userId} = auth();

  
  
  
  
 

  


  return (
    <ClerkProvider>
      <html lang="en">
        
        <body className={inter.className}>

        <StyledComponentsRegistry>
          
            <NextTopLoader
            
            color= "#27AE60"

            />

            <ThemeProvider>
              <SideBarStyleProvider>
                  <>
                    { userId && <Sidebar />}
          
                    {  <div className="w-full  rounded-lg bg-[#212121] ">

                          {children}  

                      </div>}
                    
                  </>
                </SideBarStyleProvider>
            </ThemeProvider>

        </StyledComponentsRegistry>
          
          </body>
      </html>
    </ClerkProvider>
  );
}
